### ISSUE TITLE
BCs on lines

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svFSI#41]
Has anybody tried to prescribe boundary conditions on lines (instead of surfaces)? See example project here with lines provided in `x_zero.vtp`: [line_bc.zip](https://github.com/SimVascular/svFSI/files/6933510/line_bc.zip) 

Importing the line mesh, `svFSI` fails with 
```
 <VTK XML Parser> Loading file <mesh_tube/mesh-surfaces/x_zero.vtp>
              ERROR: VTK Piece element NumberOfPolys not defined..
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR occurred, see below for more explanation
ERROR: VTP file read error (init)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by vvedula22** [comment]
@mrp089 svFSI requires elements to set boundary conditions on. For a 3D problem, it has to be surface and not a line. On the other hand, for a 2D problem, you can set BC on a line and on a point for 1D problem.

In the example you shared, you may discretize your inner face so that a face element spans across the line where you would like to apply load, i.e., the line bisects the face element. The applied load on the element would then be symmetric across the line and you should see similar deformation as if the load is applied on the line.

**Comment by vvedula22** [comment]
I also noticed that your vtp files have too much information in them unrelated to that face. Every vtp file has id's that belong to all faces. E.g., inside.vtp has ids_inside and ids_start, ids_outside, ids_end, etc. Moreover these are stored as both point-based and cell-based data. This is usually not required but is this done on purpose?

![Screenshot from 2021-08-06 04-54-18](https://user-images.githubusercontent.com/17485535/128485219-b57f0ec5-6553-472f-ba99-13f830a375cc.png)

**Comment by mrp089** [comment]
Closing this...

If you have an algebraically defined geometry (e.g. cylinder), you can apply symmetry BCs in a different way: Only simulate a fraction of the geometry, e.g. a quarter. Then apply symmetry BCs (zero x- or y-displacement) on the cut-off surfaces.

This is more reliable (and efficient) than applying BCs on lines in the interior of the domain.
