### ISSUE TITLE
Mapping values from fluid to solid mesh in FSI

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svFSI#66]
For a monolithic FSG approach using #32, I need to map WSS from the fluid interface to the solid interface.

I found the code that sets up the projection from the face pair given in the input file:
https://github.com/SimVascular/svFSI/blob/9a3ff6fb2747d208f536ea9598dce327a8f28535/Code/Source/svFSI/READMSH.f#L176-L188

It looks like this information is stored here:
https://github.com/SimVascular/svFSI/blob/9a3ff6fb2747d208f536ea9598dce327a8f28535/Code/Source/svFSI/MOD.f#L543-L547

Unfortunately, I can't find code anywhere else that maps values between fluid and solid mesh on the interface. @vvedula22 Do you have an idea how to perform this mapping? Thank you!

**Comment by vvedula22** [comment]
@mrp089 Once the interface is projected between fluid and solid domains, they both are treated as identical. So, I don't think you would need to remap quantities to the solid nodes as both the fluid and solid nodes are treated as the same at the interface. Can you be more specific about how you plan to use the mapped WSS? Would it be in the form of a vtp file? or are you creating this map internally and using it for the G&R calculations?

**Comment by mrp089** [comment]
Thanks for the hint @vvedula22 Like you said, the node numbering of solid and fluid `msh(i)%gnNo` is overlapping (i.e. containing the same ids in both, which correspond to the interface). I wrote code that finds the interface by searching for ids that are contained in both domains.

> Can you be more specific about how you plan to use the mapped WSS?

Every solid Gauss point is assigned a (transmurally constant) WSS which is used in the G&R model (compared to WSS during prestress).

> Would it be in the form of a vtp file? 

After each FSI Newton step inside svFSI, I post-process WSS and map it onto the solid domain. To read the interface-ids and update WSS in the solid domain, I use `varwallprops` by @schwarz-e (#52).

> or are you creating this map internally and using it for the G&R calculations?

I assign an "interface-id" to each node on the fluid-solid interface. Every node in the interior of the solid domain also has an interface-id, which is constant transmurally. So I can map every interface node to an interior node.

**Comment by vvedula22** [comment]
> I wrote code that finds the interface by searching for ids that are contained in both domains.

This is probably not required because, after the projection step, the `fa(iFa)%gN` and `fa(jFa)%gN` at the interface map to the same global node number in the range `1:tnNo.` 

> Every solid Gauss point is assigned a (transmurally constant) WSS which is used in the G&R model (compared to WSS during prestress).

> After each FSI Newton step inside svFSI, I post-process WSS and map it onto the solid domain. To read the interface-ids and update WSS in the solid domain, I use `varwallprops` by @schwarz-e (#52).

It appears that you want to calculate WSS at the interface from the fluid domain and access this value from the solid domain. To achieve this, you may do the following:
1. Compute WSS only at the interface as done currently in BPOST.f and store it in a global container of size `tnNo` (similar to `sF` in the subroutine `BPOST`). Let us say the interface here is characterized by iFa and iM that represents the fluid domain.
2. Now, on the solid side of the interface (characterized by jFa, jM), you may access the same WSS using `fa(jFa)%gN` as both these nodes are using the same id.
 
> I assign an "interface-id" to each node on the fluid-solid interface. Every node in the interior of the solid domain also has an interface-id, which is constant transmurally. So I can map every interface node to an interior node.

I am not sure how you transfer the quantity at the face through the thickness of the solid. It might not be a trivial problem when you have an unstructured mesh with more than one element spanning the thickness. Shouldn't you solve a Laplace problem or use a transmural distance metric to tag face quantity through all the internal elements?
