### ISSUE TITLE
Solid clamped at caps in FSI simulation?

### ISSUE THREAD

**Issue by mrp089** [SimVascular/svFSI#67]
I have this [FSI example](https://drive.google.com/file/d/1-wSDCZ0u3PGURkaiikLmp3x3NYlCMkgu/view?usp=sharing) of a quarter cylinder with steady inflow and deformable walls. For the solid, I have symmetry BCs at the cut-offs and zero longitudinal displacements on inlet and outlet.

However, when I look at the results (displacements x10), it appears that the caps of the model are clamped (i.e. zero displacements).

https://user-images.githubusercontent.com/51269309/157352852-41ddfec2-1fbf-4cb2-9d27-a1197d4f60c2.mp4

I'm not sure how this happens (might just be a stupid mistake in the input file). @fgerosa suggested it might be related to `Zero out perimeter`, but I set that to `f` for all Dirichlet BCs (fluid, solid, and mesh). @vvedula22 @ktbolt do you have any ideas?

**Comment by vvedula22** [comment]
@mrp089 I tested your case and the results show that the inflow/outflow faces are not exactly clamped. You can still see some finite displacements in the XY plane on the nodes shared with the outer wall, although these are very small. This is expected because you are forcing the flow to be along the normal direction on both these faces. 

Moreover, (a) at the outflow, you are also forcing zero tangential displacements, and (b) at inflow, you are not using `Effective direction` but applying the Dir BC along the normal direction. 

The fix for outflow is rather straightforward - simply remove the in-plane displacement constraints.

There are multiple ways to tackle the inflow:
1. Use `Effective direction` for prescribing the inflow. Then the code will impose velocity along z-direction but solve for the in-plane velocities and displacements leading to a more realistic solution. However, if you apply along the normal direction, which is the default setting, then all the degrees of freedom on this plane are set by the Dir BC and the code does not solve for in-plane components. This approach is OK for the current problem as the normal direction is the same as the z-direction but may not be possible for arbitrarily geometries.

However, note that when you use `Effective direction`, you shouldn't use a negative sign for the inflow but the actual value as,

```
   Add BC: f_start {
      Type: Dir
      Time dependence: Steady
      Value: 0.1
      Profile: User_defined
      Spatial profile file path: mesh_tube_fsi/inflow_profile.dat
      Impose flux: t
      Zero out perimeter: f
      Effective direction: (0, 0, 1)
   }
```

2. Apply Dirichlet BC on the inflow weakly. In this case, all the velocity and displacements components are solved on the inflow. This is robust as it can be applied to arbitrary geometries but involves a penalty parameter that needs to be adjusted for the problem. Usually, I start with a small value and increase it if the desired inflow BC is not obtained (e.g., if the flux is not expected).

```
   Add BC: f_start {
      Type: Dir
      Time dependence: Unsteady
      Ramp function: t
      Temporal values file path: steady_flow.dat
      Profile: User_defined
      Spatial profile file path: mesh_tube_fsi/inflow_profile.dat
      Impose flux: t
      Zero out perimeter: f
      Weakly applied: t
      Penalty parameter: 100.0
   }
```

3. Use Neumann BC instead of Dirichlet BC. This is more realistic in the sense that the inflow is some form of truncated vessel. However, getting a value of pressure at the inflow may not always be possible unlike flow rate or velocities.

Also, you might have already taken this into account but since you are solving only a part of the geometry using symmetry conditions, make sure that your flux at the inflow is also proportionally reduced so that you have consistent velocities and shear as if you are modeling the entire geometry.

**Comment by mrp089** [comment]
Thanks for all the tips, @vvedula22! These did the trick
