### ISSUE TITLE
Incorrect fluid domain volume in FSI simulation

### ISSUE THREAD

**Issue by aabrown100-git** [SimVascular/svFSI#70]
When running an FSI simulation ([02.8_no_results.zip](https://github.com/SimVascular/svFSI/files/8375361/02.8_no_results.zip)) the volume of the fluid domain (Domain 0) is calculated incorrectly. Instead, the volume output for Domain 0 is actually the volume of the total domain (fluid + solid domains). This incorrect volume is output in histor.dat during initialization, as well as in V_FS_Volume_average.txt at every time step. The volume of the solid domain (Domain 1) appears to be computed correctly.

**Comment by CZHU20** [comment]
Hi @aabrown100-git , the problem comes from incorrect bound check in volume integration function. A quick fix would be changing the input file to number your domain from 1, i.e. fluid domain id 1, solid domain id 2. For permanent fix, please check the code here:
https://github.com/CZHU20/svFSI/commit/8fdbd91bb57aab86974ae31b21ee7f2ba779a4ff
I will close the issue. Please feel free to reopen it if you have other issues.
